version: "3"
services:
  sqlserver:
    container_name: dba_sqlserver
    hostname: local.dba_sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest

    env_file:
      - ./data/envs/mssql.env

    # persistencia de dados
    volumes:
      - ./data/volumes/mssql:/var/opt/mssql

    ports:
      - 1433:1433

    networks:
      - sqlserver

    # nao gosto desse comando, se cai ele reinicia e vc fica perdido no troubleshooting. melhor cair e analisar o que aconteceu
    # restart: always

networks:
  sqlserver:
    driver: bridge